package com.toscaruntime.compiler

/**
  * This hold all tokens which are tosca keywords
  *
  * @author Minh Khang VU
  */
object Tokens {

  val definitions_version_token = "tosca_definitions_version"
  val template_name_token = "template_name"
  val template_version_token = "template_version"
  val imports_token = "imports"
  val template_author_token = "template_author"
  val description_token = "description"
  val artifact_types_token = "artifact_types"
  val mime_type_token = "mime_type"
  val relationship_types_token = "relationship_types"
  val capability_types_token = "capability_types"
  val node_types_token = "node_types"
  val data_types_token = "data_types"
  val derived_from_token = "derived_from"
  val abstract_token = "abstract"
  val tags_token = "tags"
  val properties_token = "properties"
  val attributes_token = "attributes"
  val requirements_token = "requirements"
  val capabilities_token = "capabilities"
  val artifacts_token = "artifacts"
  val interfaces_token = "interfaces"
  val type_token = "type"
  val entry_schema_token = "entry_schema"
  val required_token = "required"
  val default_token = "default"
  val constraints_token = "constraints"
  val lower_bound_token = "lower_bound"
  val upper_bound_token = "upper_bound"
  val occurrences_token = "occurrences"
  val inputs_token = "inputs"
  val outputs_token = "outputs"
  val implementation_token = "implementation"
  val operations_token = "operations"
  val valid_source_types_token = "valid_source_types"
  val valid_target_types_token = "valid_target_types"
  val valid_sources_token = "valid_sources"
  val valid_targets_token = "valid_targets"
  val file_token = "file"
  val file_ext_token = "file_ext"
  val relationship_token = "relationship"
  val relationship_type_token = "relationship_type"
  val topology_template_token = "topology_template"
  val node_templates_token = "node_templates"
  val node_token = "node"
  val capability_token = "capability"
  val value_token = "value"
  val get_input_token = "get_input"
  val get_property_token = "get_property"
  val get_attribute_token = "get_attribute"
  val get_operation_output_token = "get_operation_output"
  val concat_token = "concat"
  val equal_token: String = "equal"
  val greater_than_token = "greater_than"
  val greater_or_equal_token = "greater_or_equal"
  val less_than_token = "less_than"
  val less_or_equal_token = "less_or_equal"
  val length_token = "length"
  val min_length_token = "min_length"
  val max_length_token = "max_length"
  val pattern_token = "pattern"
  val valid_values_token = "valid_values"
  val in_range_token = "in_range"
  val group_types_token = "group_types"
  val policy_types_token = "policy_types"
  val node_filter_token = "node_filter"
}
